config:
    table_name: "{{ etl_name }}"
    bash_command: >-
      python3 {{ repo_path }}/util/templates/yfinance_daily_stock_etl_v_1.py
      --target-database asset_data_lake --target-table {{ etl_name }}
      --ticker-symbol {{ ticker_symbol }}
    schedules: 
      - "0 10 * * *"
      - "0 13 * * *"
      - "0 14 * * *"
