config:
    table_name: "asset_stock_wmt_daily"
    bash_command: >-
      python3 /home/mark/Repos/asset_data_system/util/templates/yfinance_daily_stock_etl_v_1.py
      --target-database asset_data_lake --target-table asset_stock_wmt_daily
      --ticker-symbol WMT
    schedules: 
      - "0 10 * * *"
      - "0 13 * * *"
      - "0 14 * * *"