version: '3.8'
services:
  asset_data_system_db:
    #    https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
    # sudo docker ps
    # sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' 9b99de10d575
    # mongosh --host asset_data_system_db --port 27017
    image: mongo:latest
    container_name: asset-data-system-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  asset_data_system_user:
    image: ubuntu:focal
    environment:
      IEX_TEST: true
      MONGO_HOST: asset_data_system_db
    container_name: asset-data-system-user
    links:
      - 'asset_data_system_db:database'
    restart: always
    stdin_open: true
    tty: true
    command:
      bash -c "
      apt-get update 
      && apt-get -y install sudo
      && sudo apt-get install -y wget
      && sudo apt-get install -y gnupg
      && wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
      && echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      && sudo apt-get update
      && sudo apt-get install -y mongodb-mongosh
      && sudo apt-get install -y python3
      && sudo apt-get install -y python3-pip
      && python3 -m pip install -r requirements.txt
      && /bin/bash
      "
    working_dir: /usr/local/asset-data-system
    volumes:
      - type: bind
        source: ../.
        target: /usr/local/asset-data-system

volumes:
  mongodb_data_container:

