version: '3.8'
services:
  asset_data_system_db:
    image: mongo:latest
    container_name: asset-data-system-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
  asset_data_system_user:
    image: python:3.10
    environment:
      MONGO_HOST: asset_data_system_db
      PROJECT_PATH: /usr/local/asset-data-system
    container_name: asset-data-system-user
    links:
      - 'asset_data_system_db:database'
    restart: always
    stdin_open: true
    tty: true
    command:
      bash -c "
      bash bootstrap.sh
      && python scripts/compiler
      && /bin/bash
      "
    working_dir: /usr/local/asset-data-system
    volumes:
      - type: bind
        source: ../.
        target: /usr/local/asset-data-system
      - type: bind
        source: .bash_history
        target: /root/.bash_history
  asset_data_system:
    image: python:3.10
    environment:
      MONGO_HOST: asset_data_system_db
      PROJECT_PATH: /usr/local/asset-data-system
    container_name: asset-data-system
    links:
      - 'asset_data_system_db:database'
    restart: always
    stdin_open: true
    tty: true
    command:
      bash -c "
      bash bootstrap.sh
      && python scripts/compiler
      "
    working_dir: /usr/local/asset-data-system
    volumes:
      - type: bind
        source: ../.
        target: /usr/local/asset-data-system
      - type: bind
        source: .bash_history
        target: /root/.bash_history

volumes:
  mongodb_data_container:
