config:
    table_name: "asset_stock_trmt_daily"
    associated_files:
      - file_template: "<template>/yfinance_daily_stock_etl_v_1.py"
        file_path: "<repo_path>/etl/asset/stock/trmt/daily/scripts/yfinance_daily_stock_etl_v_1.py"
      - file_template: "<template>/dag_template_1.py"
        file_path: "<airflow_path>/dags/asset_stock_trmt_daily.py"
        template_args:
          dag_name: "asset_stock_trmt_daily"
          task_id_1: "yfinance_load_table"
          bash_command_1: >-
            python3 /home/mark/Repos/asset_data_system/etl/asset/stock/trmt/daily/scripts/yfinance_daily_stock_etl_v_1.py 
            --target-database asset_data_lake --target-table asset_stock_trmt_daily 
            --ticker-symbol TRMT
