config:
    table_name: "{{ etl_name }}"
    associated_files:
      - file_template: "<template>/yfinance_daily_stock_etl_v_1.py"
        file_path: "<repo_path>/etl/{{ etl_path }}/scripts/yfinance_daily_stock_etl_v_1.py"
      - file_template: "<template>/dag_template_1.py"
        file_path: "<airflow_path>/dags/{{ etl_name }}.py"
        template_args:
          dag_name: "{{ etl_name }}"
          task_id_1: "yfinance_load_table"
          bash_command_1: >-
            python3 /home/mark/Repos/asset_data_system/etl/{{ etl_path }}/scripts/yfinance_daily_stock_etl_v_1.py 
            --target-database asset_data_lake --target-table {{ etl_name }} 
            --ticker-symbol {{ ticker_symbol }}

